// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sereno.TlDb1.DataAccess;

#nullable disable

namespace Sereno.Database.TlDb1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250131131820_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sereno.TlDb1.DataAccess.Entities.SimpleTable", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("vId");

                    b.Property<DateTime?>("Create")
                        .HasColumnType("datetime2")
                        .HasColumnName("dCreate");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("vCreateUser");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vDescription");

                    b.Property<DateTime?>("Modify")
                        .HasColumnType("datetime2")
                        .HasColumnName("dModify");

                    b.Property<string>("ModifyUser")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("vModifyUser");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("vTitle");

                    b.HasKey("Id");

                    b.ToTable("tstSimple");

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });
#pragma warning restore 612, 618
        }
    }
}
