// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sereno.Documentation.DataAccess;

#nullable disable

namespace Sereno.Documentation.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250312070908_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sereno.Documentation.DataAccess.Entities.Document", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("vId");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("vAuthor");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vContent");

                    b.Property<DateTime?>("Create")
                        .HasColumnType("datetime2")
                        .HasColumnName("dCreate");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("vCreateUser");

                    b.Property<string>("DocumentKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("vDocumentKey");

                    b.Property<string>("HtmlContent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vHtmlContent");

                    b.Property<string>("LibraryPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("vLibraryPath");

                    b.Property<DateTime?>("Modify")
                        .HasColumnType("datetime2")
                        .HasColumnName("dModify");

                    b.Property<string>("ModifyUser")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("vModifyUser");

                    b.Property<DateTime?>("NextCheck")
                        .HasColumnType("datetime2")
                        .HasColumnName("dNextCheck");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("vTitle");

                    b.HasKey("Id");

                    b.ToTable("docDocument");

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });
#pragma warning restore 612, 618
        }
    }
}
