// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sereno.Identity.DataAccess;

#nullable disable

namespace Sereno.Identity.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250514063215_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sereno.Identity.DataAccess.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("vId");

                    b.Property<string>("Create")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vCreate");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("vCreateUser");

                    b.Property<string>("Hash")
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("vHash");

                    b.Property<DateTime?>("Modify")
                        .HasColumnType("datetime2")
                        .HasColumnName("dModify");

                    b.Property<string>("ModifyUser")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("vModifyUser");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("vUserName");

                    b.HasKey("Id");

                    b.ToTable("syrUsr");

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });
#pragma warning restore 612, 618
        }
    }
}
